### ISSUE TITLE
Can't install component 41000: Rebalanced and Revised Kits due to an error

### ISSUE THREAD

**Issue by AshLancer** [Gibberlings3/TalentsOfFaerun#2]
Hi David,

I'm trying to install the Rebalanced and revised kits component of ToF beta 3 on a clean Siege of Dragonspear (no Steam/GoG) using Project Infinity, but I can't get the component to stick. The error has something to do with not being able to locate cdbrbrp2.ITM, the attack weapon used on the Shapeshifter's Greater Werewolf form. I traced the error back to kit_rebalance.tpa and found that if I renamed cdbrprp -> brbrp and cdbrbrp2 -> brbrp1, I could get the component to install, albeit with a harmless error. I didn't notice any difference in NearInfinity either, the werewolf forms all had the exact abilities detailed in your mod description.
![PI Error Message](https://github.com/Gibberlings3/TalentsOfFaerun/assets/42629680/a8b38cfe-c07c-47b5-8afb-3afb6149c5e5)
![Debug Error Message](https://github.com/Gibberlings3/TalentsOfFaerun/assets/42629680/13591e81-0896-4ab5-a438-a81207b7ae34)

**Comment by DavidMWWallace** [comment]
I don't really check bug reports here, put them on the Gibberlings 3 forums.
