### ISSUE TITLE
When selecting the Chinese installation option, the character creation interface appears in English

### ISSUE THREAD

**Issue by Lzw104522773** [Gibberlings3/TalentsOfFaerun#4]
![a74548d17bd7eaa5c79c921af87924ca](https://github.com/Gibberlings3/TalentsOfFaerun/assets/149546927/362af8ac-9300-4425-aec1-a08125405d12)

After completing the Chinese translation, I tested and checked for any installation issues on my own. After the installation was completed, in the character creation interface , Choose Multiclass, Multiclass and  its introduction are displayed in English. I took a look and here is the English version of  @ 1 and @ 2 in virtual_class.tra.

May I need you to solve the installation related issues when choosing Chinese?

**Comment by DavidMWWallace** [comment]
You need to translate sfo/lua/lang/english/virtual_class.tra.

(But NB (i) I don't check here often for bugs - better to report them on the forums at Gibberlings 3 and (ii) I'm not accepting translations till I've got a stable version of the mod.)
